pub mod aabb;
pub mod cartesian;
pub mod cellular_automata;
pub mod collections;
pub mod debug_as_display;
pub mod grid2d;
pub mod inputs;
pub mod nums;
pub mod numset;
pub mod span;
// pub mod spantree;
pub mod cube;
pub mod imap;
pub mod path;
pub mod take_upto_n;

pub mod algorithms;
pub mod comp;
pub mod iter;
pub mod nom;
pub mod numset_bytes;
pub mod points;
pub mod prelude;
